Fixed rename causing tutorial to fail.
Currently set up as if we are passing a dataframe. Tutorial fails at eemeter.metered_savings(), step 48.
TypeError: rename() got an unexpected keyword argument 'columns'

Signed-off-by: Phillips <Nathan.Phillips@dnvgl.com>